# Generated by Django 4.1 on 2022-08-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=13)),
                ('correo', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('edad', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('no_personas', models.CharField(max_length=10)),
                ('motivo', models.CharField(max_length=15)),
                ('observaciones', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
    ]
