# Generated by Django 4.1 on 2022-08-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='motivo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='observaciones',
            field=models.CharField(max_length=200),
        ),
    ]
