# Generated by Django 4.1 on 2022-08-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_solicitud_motivo_alter_solicitud_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.CharField(max_length=10),
        ),
    ]
